package tui

import (
	"fmt"
	"os"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"time"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/n-orlov/deck/internal/config"
	"github.com/n-orlov/deck/internal/theme"
)

// This file is task 013's `,` settings full-screen takeover skeleton (SPEC
// §11.5): a category list on the left, the selected category's field list
// on the right, both generated by walking internal/config.Schema rather
// than a second, hand-written field set (the exact defect requirement 22
// exists to catch). Navigation beyond "open, close" (tab/left/right/up/
// down, `/` fuzzy search), per-kind rendering, save/discard and the env-
// override label are tasks 014-018; this file only lays the frame down and
// proves it walks the schema and stays inside the terminal's budget.

// settingsCategory groups the schema fields that share one Field.Section
// under one human category name for the takeover's left-hand list.
type settingsCategory struct {
	Name    string
	Section string
	Fields  []config.Field
}

// settingsCategoryName maps a schema Field.Section to the takeover's
// human category label. Recorded here (rather than left to whichever task
// first needed a name) since task 013's notes flagged this as a decision
// to make and record: "" (config.toml's own top level) is "General", "ui"
// is "UI", "env" is "Environment" — matching config.toml's own section
// names for anything not top-level, since that is what a user editing the
// file by hand already sees.
func settingsCategoryName(section string) string {
	switch section {
	case "":
		return "General"
	case "ui":
		return "UI"
	case "env":
		return "Environment"
	case "notify":
		return "Notify"
	default:
		return strings.ToUpper(section[:1]) + section[1:]
	}
}

// settingsCategories walks config.Schema exactly once, grouping fields by
// Section in the order each section is first seen (schema.go already lists
// "", then "ui", then "env" contiguously, but this does not assume that —
// a schema field reordered or a new section inserted between others still
// groups correctly). This is the one and only place tasks 013-018 read the
// schema to build the takeover's category/field lists: neither list is
// ever hand-written alongside it.
func settingsCategories() []settingsCategory {
	var categories []settingsCategory
	indexBySection := map[string]int{}
	for _, field := range config.Schema {
		i, ok := indexBySection[field.Section]
		if !ok {
			i = len(categories)
			indexBySection[field.Section] = i
			categories = append(categories, settingsCategory{
				Name:    settingsCategoryName(field.Section),
				Section: field.Section,
			})
		}
		categories[i].Fields = append(categories[i].Fields, field)
	}
	// [notify] is deliberately absent from config.Schema (schema.go's own
	// comment: it is "the stated structural exception", edited via its own
	// dialog per §11.5 rather than flattened into fields). That dialog does
	// not exist this phase (task 029 adds no new dialog), so settings still
	// owes it "a single navigable entry" (§11.5) -- synthesized here, in the
	// TUI layer only, never added to config.Schema itself: task 018's parity
	// test walks config.Schema, and this entry has no backing schema field
	// to be found missing from.
	categories = append(categories, settingsCategory{
		Name:    settingsCategoryName("notify"),
		Section: "notify",
		Fields:  []config.Field{settingsNotifyEntry()},
	})
	return categories
}

// settingsNotifyEntry is the synthetic §11.5 "single navigable entry" for
// [notify]: a config.Field the settings takeover renders and lets the user
// select, but which config.Schema never declares and config.FileConfig has
// no member for. Its Kind is KindLink (the exact kind §11.5 reserves for
// "opens the owning dialog"), but activating it opens nothing this phase
// (task 029 adds no notification-rules dialog) -- settingsFieldValueDisplay
// and settingsActivateField both say so explicitly rather than pretending
// the link works.
func settingsNotifyEntry() config.Field {
	return config.Field{
		Section: "notify",
		Kind:    config.KindLink,
		Description: "Channels and delivery rules (SPEC §10) are structured tables " +
			"meant to be edited in their own notification-rules dialog (§11.4), not " +
			"flattened into fields here. That dialog is not implemented this phase: " +
			"this entry is honestly unavailable and opens nothing. Edit [notify] and " +
			"[[notify.rule]] by hand in config.toml until it lands.",
		Scope: config.ScopeGlobal,
	}
}

// settingsFieldLabel renders a schema Field's human label for the
// takeover's field list: the key's underscore-separated words, each
// capitalised ("recent_cwd_limit" -> "Recent Cwd Limit"). The [env] table
// field (Key == "", Section == "env") has no key to derive a label from —
// it is named for what it is instead.
func settingsFieldLabel(f config.Field) string {
	if f.Key == "" && f.Section == "notify" {
		return "Notification Rules"
	}
	if f.Key == "" {
		return "Environment Variables"
	}
	words := strings.Split(f.Key, "_")
	for i, w := range words {
		if w == "" {
			continue
		}
		words[i] = strings.ToUpper(w[:1]) + w[1:]
	}
	return strings.Join(words, " ")
}

// settingsFocus values name which of the takeover's two lists currently
// receives up/down navigation. SPEC §11.5: "tab/left/right switch between
// the category list and the field list, up/down move within the focused
// list."
const (
	settingsFocusCategories = 0
	settingsFocusFields     = 1
)

// updateSettings handles key input while the takeover is open. `/` search
// (task 014) and the discard-confirm prompt (task 016) both take over the
// whole keymap while active, so they are checked first, in the order the
// user can be in at most one of them at a time (the discard prompt only
// ever appears from the main takeover view, never from inside search).
func (m Model) updateSettings(msg tea.KeyMsg) (Model, tea.Cmd) {
	if m.settingsDiscardConfirm {
		return m.updateSettingsDiscardConfirm(msg)
	}
	// task 003's [env] entry editor (requirement 17) takes over the whole
	// keymap while active, the same way the discard-confirm prompt and `/`
	// search already do above/below -- settingsEnvEditing (typing a single
	// entry's key or value) is checked before settingsEnvOpen (browsing
	// the entries list) since the former only ever holds while the latter
	// also does.
	if m.settingsEnvEditing {
		return m.updateSettingsEnvEditing(msg)
	}
	if m.settingsEnvOpen {
		return m.updateSettingsEnvList(msg)
	}
	if m.settingsSearchActive {
		return m.updateSettingsSearch(msg)
	}
	switch msg.String() {
	case "esc":
		if m.settingsDirty() {
			m.settingsDiscardConfirm = true
			m.settingsNote = ""
		} else {
			m.settingsOpen = false
		}
	case "ctrl+s":
		m.settingsSave()
	case "tab", "left", "right":
		if m.settingsFocus == settingsFocusCategories {
			m.settingsFocus = settingsFocusFields
		} else {
			m.settingsFocus = settingsFocusCategories
		}
	case "up", "k":
		m.settingsMove(-1)
	case "down", "j":
		m.settingsMove(1)
	case "enter", " ":
		m.settingsActivateField()
	case "+", "=":
		m.settingsAdjustField(1)
	case "-", "_":
		m.settingsAdjustField(-1)
	case "/":
		m.settingsSearchActive = true
		m.settingsSearchQuery = ""
		m.settingsSearchIndex = 0
	}
	return m, nil
}

// settingsDirty reports whether the takeover's staged edits (settingsEdits)
// differ from settingsSavedEdits -- the last state actually written to
// config.toml (or, if nothing has been saved yet this session, the state
// the takeover opened with). esc uses this to decide between closing
// outright and requirement 14/20's discard-confirm prompt; comparing
// against settingsSavedEdits rather than settingsEditsFromSettings(m.
// settings) directly means a successful ctrl+s (which does not refresh
// m.settings -- that only happens on restart, per the restart-to-apply
// scope label) does not leave esc wrongly re-prompting to discard a
// change that is already safely on disk.
func (m Model) settingsDirty() bool {
	return !reflect.DeepEqual(m.settingsEdits, m.settingsSavedEdits)
}

// settingsSave is ctrl+s's effect (SPEC requirement 20): it writes every
// staged edit through config.WriteConfigFile -- task 012's atomic writer,
// so a failure here can never leave config.toml partially written or
// unparseable -- and, only on success, advances settingsSavedEdits to match
// what was just written (settingsCloneFileConfig, so a later mutation of
// settingsEdits.Env cannot alias back into the saved snapshot). A failure
// is surfaced in settingsNote rather than swallowed; settingsEdits is left
// exactly as the user had it either way, so a failed save loses nothing
// and can be retried.
func (m *Model) settingsSave() {
	path := m.settings.Paths.ConfigFile
	if path == "" {
		m.settingsNote = "save failed: no config file path is configured"
		return
	}
	if err := config.WriteConfigFile(path, m.settingsEdits); err != nil {
		m.settingsNote = "save failed: " + err.Error()
		return
	}
	m.settingsSavedEdits = settingsCloneFileConfig(m.settingsEdits)
	m.settingsNote = "saved " + path
}

// settingsCloneFileConfig deep-copies cfg's Env map (settingsCloneEnv
// already preserves nil-vs-empty exactly), so settingsSavedEdits never
// aliases the same map settingsEdits keeps mutating; every other member is
// a value type and copies by assignment.
func settingsCloneFileConfig(cfg config.FileConfig) config.FileConfig {
	cfg.Env = settingsCloneEnv(cfg.Env)
	return cfg
}

// updateSettingsDiscardConfirm handles key input while requirement 14's
// discard-confirm prompt is showing (settingsDiscardConfirm, set by esc in
// updateSettings when settingsDirty()). y/enter confirms the discard: the
// takeover closes and settingsEdits is simply dropped along with it --
// config.toml was never touched, so "what survives" is exactly what
// settingsSavedEdits/settingsNote already told the user it would be. Any
// other key (n, esc, or anything else) dismisses the prompt without losing
// the edit, returning the user to the field they were on.
func (m Model) updateSettingsDiscardConfirm(msg tea.KeyMsg) (Model, tea.Cmd) {
	switch msg.String() {
	case "y", "enter":
		m.settingsDiscardConfirm = false
		m.settingsOpen = false
		m.settingsNote = ""
	default:
		m.settingsDiscardConfirm = false
	}
	return m, nil
}

// settingsMove moves the currently focused list's selection by delta,
// wrapping like every other cycled selection in this package. Moving the
// category list resets the field index to 0, since a category swap always
// starts the field list over at its own top (mirroring settingsView's own
// "open on category 0's first field" default).
func (m *Model) settingsMove(delta int) {
	categories := settingsCategories()
	if len(categories) == 0 {
		return
	}
	switch m.settingsFocus {
	case settingsFocusCategories:
		n := len(categories)
		m.settingsCategoryIndex = (m.settingsCategoryIndex + delta + n) % n
		m.settingsFieldIndex = 0
	case settingsFocusFields:
		if m.settingsCategoryIndex < 0 || m.settingsCategoryIndex >= len(categories) {
			return
		}
		fields := categories[m.settingsCategoryIndex].Fields
		if len(fields) == 0 {
			return
		}
		n := len(fields)
		m.settingsFieldIndex = (m.settingsFieldIndex + delta + n) % n
	}
}

// settingsSelectedField returns the field the field-list focus currently
// sits on, or ok=false when categories has focus (nothing to edit there) or
// either index is out of range (an empty category, or a stale index left
// over from a category swap this call raced with the schema -- neither
// happens in practice since settingsMove always resets settingsFieldIndex
// to 0 on a category change, but settingsActivateField/settingsAdjustField
// stay defensive rather than index a slice on trust).
func (m *Model) settingsSelectedField() (config.Field, bool) {
	if m.settingsFocus != settingsFocusFields {
		return config.Field{}, false
	}
	categories := settingsCategories()
	if m.settingsCategoryIndex < 0 || m.settingsCategoryIndex >= len(categories) {
		return config.Field{}, false
	}
	fields := categories[m.settingsCategoryIndex].Fields
	if m.settingsFieldIndex < 0 || m.settingsFieldIndex >= len(fields) {
		return config.Field{}, false
	}
	return fields[m.settingsFieldIndex], true
}

// settingsActivateField is enter/space's effect on the focused field: it
// flips a KindToggle field's staged value, opens task 003's [env] entry
// editor for the KindListOfStrings [env] field (requirement 17 -- the
// field list itself has no room to edit a KEY=VALUE map inline, so enter
// hands focus to a dedicated entries list rather than leaving [env]
// display-only), and otherwise does nothing -- notably including the
// [notify] KindLink entry, which §11.5 would have open the notification-
// rules dialog if one existed. Task 029 adds no such dialog this phase, so
// activating that entry is a documented no-op rather than a key that
// silently fails to do what it claims: settingsFieldValueDisplay already
// renders that entry's value as "unavailable this phase".
func (m *Model) settingsActivateField() {
	f, ok := m.settingsSelectedField()
	if !ok {
		return
	}
	switch f.Kind {
	case config.KindToggle:
		settingsSetToggle(&m.settingsEdits, f, !settingsToggleValue(f, m.settingsEdits))
	case config.KindListOfStrings:
		if f.FullKey() == "[env]" {
			m.settingsEnvOpen = true
			m.settingsEnvIndex = 0
			m.settingsEnvEditing = false
		}
	}
}

// settingsEnvKeys returns cfg.Env's keys in a stable (sorted) order, so
// the entries list settingsEnvViewLines renders and the index
// settingsEnvIndex selects agree on which row is which across renders --
// Go map iteration order is randomised, so nothing else in this package
// may walk cfg.Env directly for display or selection.
func settingsEnvKeys(cfg config.FileConfig) []string {
	keys := make([]string, 0, len(cfg.Env))
	for k := range cfg.Env {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// updateSettingsEnvList handles key input while the [env] entries list has
// taken over the field panel (m.settingsEnvOpen, m.settingsEnvEditing
// false): up/down move the selection across every staged entry plus a
// trailing "add entry" row, enter opens the selected entry (or a blank one
// for "add entry") for editing, "-"/"_" removes the selected entry
// outright (mirroring +/-'s existing "adjust this field" verb rather than
// binding a new key the footer would have to learn to name), and esc
// leaves the entries list and returns to the field list -- no key here is
// new: every one is already bound and named by settingsFooterLine.
func (m Model) updateSettingsEnvList(msg tea.KeyMsg) (Model, tea.Cmd) {
	keys := settingsEnvKeys(m.settingsEdits)
	n := len(keys) + 1
	switch msg.String() {
	case "esc":
		m.settingsEnvOpen = false
	case "up", "k":
		m.settingsEnvIndex = (m.settingsEnvIndex - 1 + n) % n
	case "down", "j":
		m.settingsEnvIndex = (m.settingsEnvIndex + 1) % n
	case "enter", " ":
		switch {
		case m.settingsEnvIndex == len(keys):
			m.settingsEnvEditKey = ""
			m.settingsEnvEditValue = ""
			m.settingsEnvEditOriginalKey = ""
			m.settingsEnvEditingKeyPart = true
			m.settingsEnvEditing = true
		case m.settingsEnvIndex >= 0 && m.settingsEnvIndex < len(keys):
			key := keys[m.settingsEnvIndex]
			m.settingsEnvEditKey = key
			m.settingsEnvEditValue = m.settingsEdits.Env[key]
			m.settingsEnvEditOriginalKey = key
			m.settingsEnvEditingKeyPart = false
			m.settingsEnvEditing = true
		}
	case "-", "_":
		m.settingsEnvDeleteSelected()
	}
	return m, nil
}

// settingsEnvDeleteSelected removes the entries list's currently selected
// entry from m.settingsEdits.Env (never m.settingsSavedEdits -- deleting
// only stages the removal, ctrl+s/esc still govern whether it ever
// reaches config.toml, exactly like every other field kind's edit) and
// clamps settingsEnvIndex back onto the shorter list. Selecting the
// trailing "add entry" row and pressing "-" is a no-op: there is nothing
// there to remove.
func (m *Model) settingsEnvDeleteSelected() {
	keys := settingsEnvKeys(m.settingsEdits)
	if m.settingsEnvIndex < 0 || m.settingsEnvIndex >= len(keys) {
		return
	}
	delete(m.settingsEdits.Env, keys[m.settingsEnvIndex])
	n := len(settingsEnvKeys(m.settingsEdits)) + 1
	if m.settingsEnvIndex >= n {
		m.settingsEnvIndex = n - 1
	}
}

// updateSettingsEnvEditing handles key input while a single [env] entry's
// key or value is being typed (m.settingsEnvEditing): typed runes extend
// whichever of settingsEnvEditKey/settingsEnvEditValue tab currently
// targets (settingsEnvEditingKeyPart), backspace shortens it, tab swaps
// which one is being typed, enter on the key moves to the value without
// committing yet and enter on the value commits the whole entry
// (settingsEnvCommitEdit) and returns to the entries list, and esc
// discards the buffer and returns to the entries list without touching
// settingsEdits.Env at all.
func (m Model) updateSettingsEnvEditing(msg tea.KeyMsg) (Model, tea.Cmd) {
	switch msg.String() {
	case "esc":
		m.settingsEnvEditing = false
		return m, nil
	case "tab":
		m.settingsEnvEditingKeyPart = !m.settingsEnvEditingKeyPart
		return m, nil
	case "enter":
		if m.settingsEnvEditingKeyPart {
			m.settingsEnvEditingKeyPart = false
			return m, nil
		}
		m.settingsEnvCommitEdit()
		m.settingsEnvEditing = false
		return m, nil
	case "backspace", "ctrl+h":
		if m.settingsEnvEditingKeyPart {
			if r := []rune(m.settingsEnvEditKey); len(r) > 0 {
				m.settingsEnvEditKey = string(r[:len(r)-1])
			}
		} else {
			if r := []rune(m.settingsEnvEditValue); len(r) > 0 {
				m.settingsEnvEditValue = string(r[:len(r)-1])
			}
		}
		return m, nil
	}
	if runes := msg.Runes; len(runes) > 0 {
		if m.settingsEnvEditingKeyPart {
			m.settingsEnvEditKey += string(runes)
		} else {
			m.settingsEnvEditValue += string(runes)
		}
	}
	return m, nil
}

// settingsEnvCommitEdit stages the currently-edited [env] entry into
// m.settingsEdits.Env: an empty (after trimming) key commits nothing --
// updateSettingsEnvEditing still leaves editing mode, so an operator who
// backspaces a key to nothing and hits enter simply abandons the entry
// rather than staging a blank-named variable. A non-empty key that
// differs from settingsEnvEditOriginalKey (a rename, or a brand new entry
// where the original is "") removes the original key first, so renaming
// never leaves both the old and new key staged at once. settingsEnvIndex
// is left on the committed entry's row in the entries list's own sorted
// order.
func (m *Model) settingsEnvCommitEdit() {
	key := strings.TrimSpace(m.settingsEnvEditKey)
	if key == "" {
		return
	}
	if m.settingsEdits.Env == nil {
		m.settingsEdits.Env = map[string]string{}
	}
	if m.settingsEnvEditOriginalKey != "" && m.settingsEnvEditOriginalKey != key {
		delete(m.settingsEdits.Env, m.settingsEnvEditOriginalKey)
	}
	m.settingsEdits.Env[key] = m.settingsEnvEditValue
	for i, k := range settingsEnvKeys(m.settingsEdits) {
		if k == key {
			m.settingsEnvIndex = i
			break
		}
	}
}

// settingsAdjustField is +/-'s effect on the focused field: step a
// KindInteger field's staged value by delta (settingsSetInteger clamps to
// the field's declared Bounds, so this can never stage a value the file
// writer or the schema-driven parser would reject), or cycle a KindEnum
// field's staged value through settingsFieldOptions. Every other kind has
// no notion of a "next" value and is left untouched.
func (m *Model) settingsAdjustField(delta int) {
	f, ok := m.settingsSelectedField()
	if !ok {
		return
	}
	switch f.Kind {
	case config.KindInteger:
		settingsSetInteger(&m.settingsEdits, f, settingsIntegerValue(f, m.settingsEdits)+delta)
	case config.KindEnum:
		options := m.settingsFieldOptions(f)
		if len(options) == 0 {
			return
		}
		cur := settingsEnumValue(f, m.settingsEdits)
		idx := 0
		for i, o := range options {
			if o == cur {
				idx = i
			}
		}
		idx = ((idx+delta)%len(options) + len(options)) % len(options)
		settingsSetEnum(&m.settingsEdits, f, options[idx])
	}
}

// settingsEditsFromSettings seeds the takeover's staged working copy
// (Model.settingsEdits) from the already-resolved config.Settings the rest
// of the program uses, the one time it needs to: when `,` opens the
// takeover. Every member here mirrors a real config.FileConfig member a
// real Settings field was itself loaded from (see config.Settings' own
// doc comments) -- Theme is the one exception, since Settings keeps only
// the already-*resolved* theme.Theme plus a fallback reason, not the raw
// configured name; m.settings.Theme.Name (the resolved theme actually in
// effect) is the closest honest approximation available without re-reading
// config.toml's raw ui.theme value here.
func settingsEditsFromSettings(s config.Settings) config.FileConfig {
	themeName := ""
	if s.Theme != nil {
		themeName = s.Theme.Name
	}
	return config.FileConfig{
		AllowYolo:          s.AllowYolo,
		StaleAfter:         s.StaleAfter,
		CaptureMinInterval: s.CaptureMinInterval,
		ASCII:              s.ASCII,
		Mouse:              s.Mouse,
		RecentCwdLimit:     s.RecentCwdLimit,
		Theme:              themeName,
		Env:                settingsCloneEnv(s.Env),
	}
}

func settingsCloneEnv(env map[string]string) map[string]string {
	if env == nil {
		return nil
	}
	out := make(map[string]string, len(env))
	for k, v := range env {
		out[k] = v
	}
	return out
}

// settingsToggleValue/settingsSetToggle, settingsIntegerValue/
// settingsSetInteger and settingsEnumValue/settingsSetEnum are the get/set
// pair for every KindToggle/KindInteger/KindEnum field config.Schema
// actually declares today. Each mirrors toml.go's setField and
// toml_write.go's serializeFieldValue: one generic dispatch per Kind, with
// a FullKey switch beneath it that carries no logic of its own (Go structs
// have no by-name-string field access without reflection) -- adding a
// future schema field of an already-supported kind means one case here,
// not a new code path.
func settingsToggleValue(f config.Field, cfg config.FileConfig) bool {
	switch f.FullKey() {
	case "allow_yolo":
		return cfg.AllowYolo
	case "ui.ascii":
		return cfg.ASCII
	case "ui.mouse":
		return cfg.Mouse
	default:
		b, _ := f.Default.(bool)
		return b
	}
}

func settingsSetToggle(cfg *config.FileConfig, f config.Field, v bool) {
	switch f.FullKey() {
	case "allow_yolo":
		cfg.AllowYolo = v
	case "ui.ascii":
		cfg.ASCII = v
	case "ui.mouse":
		cfg.Mouse = v
	}
}

func settingsIntegerValue(f config.Field, cfg config.FileConfig) int {
	switch f.FullKey() {
	case "stale_after":
		return int(cfg.StaleAfter.Seconds())
	case "capture_min_interval":
		return int(cfg.CaptureMinInterval.Seconds())
	case "ui.recent_cwd_limit":
		return cfg.RecentCwdLimit
	default:
		v, _ := f.Default.(int)
		return v
	}
}

// settingsSetInteger clamps v to field's declared IntBounds before writing
// it into cfg, so +/- (or a future direct-entry editor) can never stage an
// out-of-bounds value the atomic writer or the schema-driven reader would
// then have to reject on the next load.
func settingsSetInteger(cfg *config.FileConfig, f config.Field, v int) {
	if v < f.IntBounds.Min {
		v = f.IntBounds.Min
	}
	if f.IntBounds.Max != nil && v > *f.IntBounds.Max {
		v = *f.IntBounds.Max
	}
	switch f.FullKey() {
	case "stale_after":
		cfg.StaleAfter = time.Duration(v) * time.Second
	case "capture_min_interval":
		cfg.CaptureMinInterval = time.Duration(v) * time.Second
	case "ui.recent_cwd_limit":
		cfg.RecentCwdLimit = v
	}
}

func settingsEnumValue(f config.Field, cfg config.FileConfig) string {
	switch f.FullKey() {
	case "ui.theme":
		return cfg.Theme
	default:
		s, _ := f.Default.(string)
		return s
	}
}

func settingsSetEnum(cfg *config.FileConfig, f config.Field, v string) {
	switch f.FullKey() {
	case "ui.theme":
		cfg.Theme = v
	}
}

// settingsFieldOptions resolves a KindEnum field's cycle-through choices.
// ui.theme is §11.6's DynamicEnum case (schema.go: "the schema cannot list
// a fixed choice set because a dropped-in user theme file changes it
// without a code change"), so its options are resolved here, at render/
// edit time, from the same theme.Builtins()/theme.DiscoverUserThemes the
// rest of the program uses to resolve a configured name -- never a second,
// hand-maintained theme name list.
func (m Model) settingsFieldOptions(f config.Field) []string {
	switch f.FullKey() {
	case "ui.theme":
		return settingsThemeOptions(m.settings.Paths)
	default:
		return f.EnumValues
	}
}

func settingsThemeOptions(paths config.Paths) []string {
	var names []string
	for _, t := range theme.Builtins() {
		names = append(names, t.Name)
	}
	sort.Strings(names)
	userThemes, _ := theme.DiscoverUserThemes(theme.ThemesDir(paths.ConfigFile))
	var userNames []string
	for name := range userThemes {
		userNames = append(userNames, name)
	}
	sort.Strings(userNames)
	return append(names, userNames...)
}

// settingsFieldValueDisplay renders field f's current staged value (from
// cfg) exactly as §11.5 requires per kind: On/Off for a toggle, the number
// plus its declared unit and bounds for a bounded integer, the raw string
// for a plain string, a path collapsed back to `~` form for KindPath (the
// display-side counterpart of expandCreateCWD's ~-expansion, task 011.7),
// the selected choice for an enum, an entry count for list-of-strings, and
// the honest "unavailable this phase" for [notify]'s KindLink entry rather
// than a value it does not have. Every kind config.FieldKind names is
// handled explicitly, including the three (string, path, link other than
// notify) config.Schema happens not to use today, so a future schema
// addition of one of those kinds renders correctly on day one.
// settingsFieldEnvOverride reports whether config.Settings.EnvOverrides
// (§6.5: "Environment always outranks the file") named f as overridden in
// THIS environment, and by which DECK_* variable, so both the field row
// (settingsFieldLabel's caller) and its detail lines (settingsField
// DetailLines) can say so without a second, hand-maintained copy of which
// keys env can override -- the map config.LoadFrom already built while
// resolving env-over-file precedence is the only source of truth read
// here.
func settingsFieldEnvOverride(f config.Field, s config.Settings) (string, bool) {
	if len(s.EnvOverrides) == 0 {
		return "", false
	}
	envVar, ok := s.EnvOverrides[f.FullKey()]
	return envVar, ok
}

func settingsFieldValueDisplay(f config.Field, cfg config.FileConfig) string {
	switch f.Kind {
	case config.KindToggle:
		if settingsToggleValue(f, cfg) {
			return "On"
		}
		return "Off"
	case config.KindInteger:
		v := settingsIntegerValue(f, cfg)
		text := strconv.Itoa(v)
		if f.Unit != "" {
			text += " " + f.Unit
		}
		if bounds := settingsIntegerBoundsText(f); bounds != "" {
			text += " (" + bounds + ")"
		}
		return text
	case config.KindEnum:
		v := settingsEnumValue(f, cfg)
		if v == "" {
			return "(default)"
		}
		return v
	case config.KindString:
		return settingsStringValue(f, cfg)
	case config.KindPath:
		return settingsCollapseTilde(settingsStringValue(f, cfg))
	case config.KindListOfStrings:
		return settingsListValueDisplay(f, cfg)
	case config.KindLink:
		if f.Section == "notify" {
			return "unavailable this phase"
		}
		return "opens its own dialog"
	default:
		return fmt.Sprintf("%v", f.Default)
	}
}

// settingsIntegerBoundsText renders a KindInteger field's declared Bounds
// as the parenthetical settingsFieldValueDisplay appends, e.g. "1-50" or
// "min 1" when there is no documented upper bound (Bounds.Max == nil).
func settingsIntegerBoundsText(f config.Field) string {
	if f.Kind != config.KindInteger {
		return ""
	}
	if f.IntBounds.Max != nil {
		return fmt.Sprintf("%d-%d", f.IntBounds.Min, *f.IntBounds.Max)
	}
	return fmt.Sprintf("min %d", f.IntBounds.Min)
}

// settingsStringValue is KindString's get, generic across any future
// schema field of that kind: config.Schema declares none today, so this
// only ever falls through to the field's declared Default, but the
// dispatch shape matches settingsToggleValue/settingsIntegerValue/
// settingsEnumValue exactly so adding a real KindString field later is one
// case here, not a new function.
func settingsStringValue(f config.Field, cfg config.FileConfig) string {
	_ = cfg // no schema field of KindString exists yet to read out of cfg
	switch f.FullKey() {
	default:
		s, _ := f.Default.(string)
		return s
	}
}

// settingsCollapseTilde is the display-side inverse of tui.go's
// expandCreateCWD: a path under the current user's home directory renders
// with that prefix collapsed to `~`, matching how a user who typed `~/...`
// into a path field would expect to see it read back, rather than the
// fully-expanded absolute form expandCreateCWD stores. A path outside the
// home directory, or one os.UserHomeDir cannot resolve, is returned
// unchanged.
func settingsCollapseTilde(path string) string {
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		return path
	}
	if path == home {
		return "~"
	}
	if strings.HasPrefix(path, home+string(os.PathSeparator)) {
		return "~" + path[len(home):]
	}
	return path
}

// settingsListValueDisplay is KindListOfStrings' get. [env] (Key == "") is
// the one real schema field of this kind: its "list" is really a
// KEY=VALUE map, so rendering every entry inline would crowd the field
// list (and leak env values into a screenshot); an entry count is shown
// instead, matching §11.5's own framing of [env] as "opens" the concept of
// many entries rather than one flat value (the actual per-entry editor
// this implies is out of scope for task 015, which owns per-kind display,
// not a nested table editor -- see settingsFieldDetailLines' description
// text for the honest statement of what changing it does).
func settingsListValueDisplay(f config.Field, cfg config.FileConfig) string {
	if f.FullKey() == "[env]" {
		n := len(cfg.Env)
		switch n {
		case 0:
			return "0 entries"
		case 1:
			return "1 entry"
		default:
			return fmt.Sprintf("%d entries", n)
		}
	}
	if list, ok := f.Default.([]string); ok {
		if len(list) == 0 {
			return "(empty)"
		}
		return strings.Join(list, ", ")
	}
	return "(empty)"
}

// settingsFieldDetailLines renders the currently selected field's kind,
// scope and description underneath its own row in the field list --
// §11.5's "each field states what it does and what changes when it
// changes" plus the scope label requirement, both read verbatim off the
// schema Field rather than a second, hand-written copy of either. width is
// the field panel's usable content width; wrapText keeps a long
// description from being truncated away instead of wrapped across lines.
func settingsFieldDetailLines(f config.Field, width int, envVar string) []string {
	if width < 1 {
		width = 1
	}
	lines := []string{fmt.Sprintf("Kind: %s \u00b7 Scope: %s", f.Kind, f.Scope)}
	if envVar != "" {
		lines = append(lines, wrapText(fmt.Sprintf("Overridden by environment: %s is set, so the running value comes from %s, not this file. Editing and saving here writes config.toml, but the running value keeps coming from %s until it is unset.", envVar, envVar, envVar), width)...)
	}
	lines = append(lines, wrapText(f.Description, width)...)
	return lines
}

// settingsSearchResult pairs a schema field matched by a `/` query with the
// category/field indices selecting it (enter, task 014) or rendering it
// (task 015) lands on.
type settingsSearchResult struct {
	CategoryIndex int
	FieldIndex    int
	Field         config.Field
}

// settingsFuzzyMatch is the small "fuzzy" §11.5's field search needs: every
// whitespace-separated token of query must appear as a case-insensitive
// substring of target, in any order. A query of "" matches everything (the
// search box starts empty and shows every field until the user types).
func settingsFuzzyMatch(query, target string) bool {
	target = strings.ToLower(target)
	for _, tok := range strings.Fields(strings.ToLower(query)) {
		if !strings.Contains(target, tok) {
			return false
		}
	}
	return true
}

// settingsSearchMatches searches every schema field's label AND
// description (§11.5: "/ ... searches every field by label and
// description") and returns matches in schema order, each carrying the
// category/field indices that select it.
func settingsSearchMatches(query string) []settingsSearchResult {
	var results []settingsSearchResult
	for ci, cat := range settingsCategories() {
		for fi, f := range cat.Fields {
			label := settingsFieldLabel(f)
			if settingsFuzzyMatch(query, label) || settingsFuzzyMatch(query, f.Description) {
				results = append(results, settingsSearchResult{CategoryIndex: ci, FieldIndex: fi, Field: f})
			}
		}
	}
	return results
}

// updateSettingsSearch handles key input while the `/` search box is
// active: typed runes extend the query, backspace shortens it, up/down
// move among the current matches, enter jumps the two lists to the
// highlighted match and leaves search mode with focus on the field list,
// and esc leaves search mode (clearing the query) without moving the
// selection -- mirroring the closing-without-saving shape task 016 will
// give the takeover as a whole, but scoped to just the search box.
func (m Model) updateSettingsSearch(msg tea.KeyMsg) (Model, tea.Cmd) {
	switch msg.String() {
	case "esc":
		m.settingsSearchActive = false
		m.settingsSearchQuery = ""
		m.settingsSearchIndex = 0
		return m, nil
	case "enter":
		results := settingsSearchMatches(m.settingsSearchQuery)
		if m.settingsSearchIndex >= 0 && m.settingsSearchIndex < len(results) {
			match := results[m.settingsSearchIndex]
			m.settingsCategoryIndex = match.CategoryIndex
			m.settingsFieldIndex = match.FieldIndex
			m.settingsFocus = settingsFocusFields
		}
		m.settingsSearchActive = false
		m.settingsSearchQuery = ""
		m.settingsSearchIndex = 0
		return m, nil
	case "backspace", "ctrl+h":
		if q := m.settingsSearchQuery; q != "" {
			r := []rune(q)
			m.settingsSearchQuery = string(r[:len(r)-1])
		}
		m.settingsSearchIndex = 0
		return m, nil
	case "up", "ctrl+p":
		if n := len(settingsSearchMatches(m.settingsSearchQuery)); n > 0 {
			m.settingsSearchIndex = (m.settingsSearchIndex - 1 + n) % n
		}
		return m, nil
	case "down", "ctrl+n":
		if n := len(settingsSearchMatches(m.settingsSearchQuery)); n > 0 {
			m.settingsSearchIndex = (m.settingsSearchIndex + 1) % n
		}
		return m, nil
	}
	if runes := msg.Runes; len(runes) > 0 {
		m.settingsSearchQuery += string(runes)
		m.settingsSearchIndex = 0
	}
	return m, nil
}

// settingsCategoryWidth picks the left category panel's width the same way
// ComputeLayout picks the sidebar's: a fraction of the total width, clamped
// to a floor that keeps every category name legible and a ceiling that
// leaves the field list (the panel that actually carries the field's
// description text, task 015) the majority of the screen.
func settingsCategoryWidth(width int) int {
	w := width / 3
	const floor, ceil = 20, 30
	if w < floor {
		w = floor
	}
	if w > ceil {
		w = ceil
	}
	if width-w < floor {
		w = width - floor
	}
	if w < 1 {
		w = 1
	}
	return w
}

// settingsRowSegment pairs one run of text with the theme token it renders
// in, so settingsRenderRow can compose a "label: value" row (SPEC
// requirement 34: labels in `hint`, values in `text`) as several
// differently-coloured runs on one line.
type settingsRowSegment struct {
	Text string
	Tok  theme.Token
}

// settingsRenderRow composes segs into one coloured line, opening bg
// (SPEC requirement 42's selection/selection_idle focus cue) once at the
// very start when selected is true, then each segment's own foreground
// token, and closing with exactly ONE trailing full reset at the end --
// never one reset per segment. An SGR \x1b[0m reset clears every
// attribute, background included, so stacking colorToken's own
// self-resetting calls here would silently cancel the outer row
// background the moment the first inner foreground segment ended;
// opening progressively and resetting once keeps the background live
// under every segment's text.
func (m Model) settingsRenderRow(segs []settingsRowSegment, bg theme.Token, selected bool) string {
	if !m.settings.Color {
		var b strings.Builder
		for _, s := range segs {
			b.WriteString(s.Text)
		}
		return b.String()
	}
	var b strings.Builder
	opened := false
	if selected {
		if seq, ok := m.backgroundSGR(bg); ok {
			b.WriteString(seq)
			opened = true
		}
	}
	for _, s := range segs {
		if seq, ok := m.foregroundSGR(s.Tok); ok {
			b.WriteString(seq)
			opened = true
		}
		b.WriteString(s.Text)
	}
	if opened {
		b.WriteString("\x1b[0m")
	}
	return b.String()
}

// settingsSelectionToken resolves which of SPEC requirement 42's two
// focus-cue tokens a list's currently-selected row renders in: `selection`
// when that list is the one tab/left/right currently gives up/down to,
// `selection_idle` otherwise -- both lists always show their own
// highlighted row, distinguished by which token, never by one list's
// highlight disappearing outright.
func (m Model) settingsSelectionToken(list int) theme.Token {
	if m.settingsFocus == list {
		return theme.Selection
	}
	return theme.SelectionIdle
}

// settingsBorderColor renders a border glyph run in `border_focus` (SPEC
// requirement 42) when the panel it belongs to is the one currently
// focused, or `border` otherwise. The settings takeover's two lists are
// deck's only second focusable surface -- §11.3's main view has exactly
// one focusable region, which is why `tab` is unbound there (requirement
// 42). Task 021 generalised the same border_focus/border split to every
// other panel this package draws (panel.go's borderColor, now token-
// parametrised rather than the old removed placeholder m.color()); this
// remains
// its own function only because the settings takeover's focus state
// (m.settingsFocus, not "is this the sidebar or the preview") is what
// picks the token here.
func (m Model) settingsBorderColor(focused bool, text string) string {
	tok := theme.Border
	if focused {
		tok = theme.BorderFocus
	}
	return m.colorToken(tok, text)
}

// settingsLeftTopLine/settingsLeftBottomLine/settingsLeftContentLine draw
// the category panel's (left, sidebar-shaped) border with the focus cue
// above; geometry matches panel.go's sidebarTopLine/sidebarBottomLine/
// sidebarContentLine exactly -- only the colour source differs.
func (m Model) settingsLeftTopLine(width int, title string, focused bool) string {
	bc := m.box()
	inner := width - 1
	label, remain := m.borderLabel(title, inner)
	return m.settingsBorderColor(focused, bc.topLeft) + label + m.settingsBorderColor(focused, strings.Repeat(bc.horizontal, remain))
}

func (m Model) settingsLeftBottomLine(width int, focused bool) string {
	bc := m.box()
	return m.settingsBorderColor(focused, bc.bottomLeft) + m.settingsBorderColor(focused, strings.Repeat(bc.horizontal, width-1))
}

func (m Model) settingsLeftContentLine(width int, text string, focused bool) string {
	bc := m.box()
	return m.settingsBorderColor(focused, bc.vertical) + " " + m.padTrunc(text, width-3) + " "
}

// settingsRightTopLine/settingsRightBottomLine/settingsRightContentLine
// mirror panel.go's previewTopLine/previewBottomLine/previewContentLine
// with seam=true (the settings takeover is always side-by-side, never
// stacked) but the focus-cue colour source above instead of borderColor.
func (m Model) settingsRightTopLine(width int, title string, focused bool) string {
	bc := m.box()
	inner := width - 2
	label, remain := m.borderLabel(title, inner)
	return m.settingsBorderColor(focused, bc.seamTop) + label + m.settingsBorderColor(focused, strings.Repeat(bc.horizontal, remain)) + m.settingsBorderColor(focused, bc.topRight)
}

func (m Model) settingsRightBottomLine(width int, focused bool) string {
	bc := m.box()
	inner := width - 2
	return m.settingsBorderColor(focused, bc.seamBottom) + m.settingsBorderColor(focused, strings.Repeat(bc.horizontal, inner)) + m.settingsBorderColor(focused, bc.bottomRight)
}

func (m Model) settingsRightContentLine(width int, text string, focused bool) string {
	bc := m.box()
	inner := width - 4
	return m.settingsBorderColor(focused, bc.vertical) + " " + m.padTrunc(text, inner) + " " + m.settingsBorderColor(focused, bc.vertical)
}

// settingsView renders the full-screen takeover: a category list panel and
// a field list panel sharing one seam. Geometry (corner/seam glyphs,
// column widths) matches panel.go's sidebarTopLine/sidebarContentLine/
// sidebarBottomLine and previewTopLine/previewContentLine/previewBottomLine
// exactly — SPEC requirement 16's "bordered like every other panel, dialog
// and overlay" with one geometry, not two — but colour comes from the
// settingsLeft*/settingsRight*/settingsRenderRow helpers above so the two
// lists' focus cue (border_focus/border, selection/selection_idle, SPEC
// requirement 42) and the field rows' label/value distinction (`hint`/
// `text`, requirement 34) render from theme tokens rather than the
// colourless placeholder tasks 013-018 left in place.
func (m Model) settingsView() string {
	width, height := m.frameSize()
	leftWidth := settingsCategoryWidth(width)
	rightWidth := width - leftWidth
	// One row for the top border, one for the bottom border, one for the
	// footer line below the frame (mirroring mainView's own footerLine).
	contentRows := height - 3
	if contentRows < 0 {
		contentRows = 0
	}

	categories := settingsCategories()
	leftFocused := m.settingsFocus == settingsFocusCategories
	rightFocused := m.settingsFocus == settingsFocusFields

	if m.settingsSearchActive {
		return m.settingsSearchViewLines(categories, leftWidth, rightWidth, contentRows, height)
	}
	if m.settingsEnvOpen {
		return m.settingsEnvViewLines(categories, leftWidth, rightWidth, contentRows, height)
	}

	categorySelTok := m.settingsSelectionToken(settingsFocusCategories)
	leftLines := make([]string, len(categories))
	for i, cat := range categories {
		marker := "  "
		selected := i == m.settingsCategoryIndex
		if selected {
			marker = "> "
		}
		leftLines[i] = m.settingsRenderRow([]settingsRowSegment{{Text: marker + cat.Name, Tok: theme.Text}}, categorySelTok, selected)
	}
	leftLines = fitLines(leftLines, contentRows)

	fieldSelTok := m.settingsSelectionToken(settingsFocusFields)
	var rightLines []string
	if m.settingsCategoryIndex >= 0 && m.settingsCategoryIndex < len(categories) {
		fields := categories[m.settingsCategoryIndex].Fields
		innerWidth := rightWidth - 4
		for i, f := range fields {
			marker := "  "
			selected := i == m.settingsFieldIndex
			if selected {
				marker = "> "
			}
			segs := []settingsRowSegment{
				{Text: marker, Tok: theme.Text},
				{Text: settingsFieldLabel(f), Tok: theme.Hint},
				{Text: ": ", Tok: theme.Text},
				{Text: settingsFieldValueDisplay(f, m.settingsEdits), Tok: theme.Text},
			}
			if envVar, ok := settingsFieldEnvOverride(f, m.settings); ok {
				segs = append(segs, settingsRowSegment{Text: " (overridden by environment: " + envVar + ")", Tok: theme.Text})
			}
			rightLines = append(rightLines, m.settingsRenderRow(segs, fieldSelTok, selected))
			if selected {
				envVar, _ := settingsFieldEnvOverride(f, m.settings)
				for _, detail := range settingsFieldDetailLines(f, innerWidth-2, envVar) {
					rightLines = append(rightLines, "    "+detail)
				}
			}
		}
	}
	rightLines = fitLines(rightLines, contentRows)

	lines := make([]string, 0, height)
	lines = append(lines, m.settingsLeftTopLine(leftWidth, "Categories", leftFocused)+m.settingsRightTopLine(rightWidth, "Fields", rightFocused))
	for i := 0; i < contentRows; i++ {
		lines = append(lines, m.settingsLeftContentLine(leftWidth, leftLines[i], leftFocused)+m.settingsRightContentLine(rightWidth, rightLines[i], rightFocused))
	}
	lines = append(lines, m.settingsLeftBottomLine(leftWidth, leftFocused)+m.settingsRightBottomLine(rightWidth, rightFocused))
	lines = append(lines, m.settingsFooterLine())
	return strings.Join(lines, "\n")
}

// settingsFooterLine names every key the takeover currently binds:
// task 013's esc, task 014's tab/left/right/up-down/`/`, task 015's
// enter/space (toggle) and +/- (adjust a bounded integer or cycle an
// enum), and task 016's ctrl+s (save) -- never a key bound here but left
// unnamed, the same "advertises a key it doesn't grant"/"binds a key it
// doesn't name" defect the §11.4 dialog contract (task 029) forbids for
// the five dialogs. While the discard-confirm prompt or `/` search is
// active, the line instead names only the keys valid in that sub-mode.
func (m Model) settingsFooterLine() string {
	width, _ := m.frameSize()
	if m.settingsDiscardConfirm {
		return truncateToWidth("discard unsaved changes and keep config.toml as last saved? y/enter discards - any other key cancels", width)
	}
	if m.settingsSearchActive {
		return truncateToWidth("type to search - up/down select - enter jump - esc cancel", width)
	}
	if m.settingsEnvEditing {
		return truncateToWidth("type to edit - tab switch key/value - enter on value saves the entry - esc cancels", width)
	}
	if m.settingsEnvOpen {
		return truncateToWidth("up/down move - enter edit/add - - remove - esc back to fields", width)
	}
	footer := "tab/left/right switch - up/down move - enter/+/- edit - / search - ctrl+s save - esc close"
	if m.settingsNote != "" {
		footer = m.settingsNote + " - " + footer
	}
	return truncateToWidth(footer, width)
}

// settingsEnvViewLines renders the takeover while task 003's [env] entry
// editor has taken over the field panel (m.settingsEnvOpen): the left
// panel keeps showing the category list unchanged and unfocused (editing
// [env] never moves the category selection), and the right panel becomes
// the entries list -- one row per m.settingsEdits.Env key in
// settingsEnvKeys' stable order, each rendered "KEY=VALUE", plus a
// trailing "+ add entry" row -- or, while m.settingsEnvEditing is also
// true, the single key/value being typed with the field currently
// receiving keystrokes named so an operator mid-edit can see which of the
// two tab currently targets.
func (m Model) settingsEnvViewLines(categories []settingsCategory, leftWidth, rightWidth, contentRows, height int) string {
	const leftFocused, rightFocused = false, true

	leftLines := make([]string, len(categories))
	for i, cat := range categories {
		leftLines[i] = m.settingsRenderRow([]settingsRowSegment{{Text: "  " + cat.Name, Tok: theme.Text}}, theme.SelectionIdle, false)
	}
	leftLines = fitLines(leftLines, contentRows)

	var rightLines []string
	var title string
	if m.settingsEnvEditing {
		title = "Edit [env] entry"
		keyMarker, valueMarker := "  ", "  "
		if m.settingsEnvEditingKeyPart {
			keyMarker = "> "
		} else {
			valueMarker = "> "
		}
		rightLines = []string{
			m.settingsRenderRow([]settingsRowSegment{{Text: keyMarker + "Key: " + m.settingsEnvEditKey, Tok: theme.Text}}, theme.Selection, m.settingsEnvEditingKeyPart),
			m.settingsRenderRow([]settingsRowSegment{{Text: valueMarker + "Value: " + m.settingsEnvEditValue, Tok: theme.Text}}, theme.Selection, !m.settingsEnvEditingKeyPart),
		}
	} else {
		title = "[env]"
		keys := settingsEnvKeys(m.settingsEdits)
		rightLines = make([]string, 0, len(keys)+1)
		for i, k := range keys {
			marker := "  "
			selected := i == m.settingsEnvIndex
			if selected {
				marker = "> "
			}
			segs := []settingsRowSegment{
				{Text: marker, Tok: theme.Text},
				{Text: k, Tok: theme.Hint},
				{Text: "=", Tok: theme.Text},
				{Text: m.settingsEdits.Env[k], Tok: theme.Text},
			}
			rightLines = append(rightLines, m.settingsRenderRow(segs, theme.Selection, selected))
		}
		addMarker := "  "
		addSelected := m.settingsEnvIndex == len(keys)
		if addSelected {
			addMarker = "> "
		}
		rightLines = append(rightLines, m.settingsRenderRow([]settingsRowSegment{{Text: addMarker + "+ add entry", Tok: theme.Hint}}, theme.Selection, addSelected))
	}
	rightLines = fitLines(rightLines, contentRows)

	lines := make([]string, 0, height)
	lines = append(lines, m.settingsLeftTopLine(leftWidth, "Categories", leftFocused)+m.settingsRightTopLine(rightWidth, title, rightFocused))
	for i := 0; i < contentRows; i++ {
		lines = append(lines, m.settingsLeftContentLine(leftWidth, leftLines[i], leftFocused)+m.settingsRightContentLine(rightWidth, rightLines[i], rightFocused))
	}
	lines = append(lines, m.settingsLeftBottomLine(leftWidth, leftFocused)+m.settingsRightBottomLine(rightWidth, rightFocused))
	lines = append(lines, m.settingsFooterLine())
	return strings.Join(lines, "\n")
}

// settingsSearchViewLines renders the takeover while `/`'s search box is
// active: the left panel keeps showing the category list unchanged (search
// spans every category, so no single category is "selected" while
// searching), and the right panel's title carries the typed query and its
// content becomes the flat, cross-category list settingsSearchMatches
// returns, each row prefixed with its own category name so a match from a
// category other than the one open before `/` was pressed is not mistaken
// for one of the still-shown left panel's category.
func (m Model) settingsSearchViewLines(categories []settingsCategory, leftWidth, rightWidth, contentRows, height int) string {
	// Search spans every category, so the left (category) list is never
	// the one up/down moves within -- it stays unfocused (`border`) for
	// the whole duration of search, and the right (results) panel, which
	// up/down does move within, carries the focus cue (`border_focus`).
	const leftFocused, rightFocused = false, true

	leftLines := make([]string, len(categories))
	for i, cat := range categories {
		leftLines[i] = m.settingsRenderRow([]settingsRowSegment{{Text: "  " + cat.Name, Tok: theme.Text}}, theme.SelectionIdle, false)
	}
	leftLines = fitLines(leftLines, contentRows)

	results := settingsSearchMatches(m.settingsSearchQuery)
	rightLines := make([]string, len(results))
	for i, r := range results {
		marker := "  "
		selected := i == m.settingsSearchIndex
		if selected {
			marker = "> "
		}
		segs := []settingsRowSegment{
			{Text: marker + categories[r.CategoryIndex].Name + ": ", Tok: theme.Text},
			{Text: settingsFieldLabel(r.Field), Tok: theme.Hint},
		}
		rightLines[i] = m.settingsRenderRow(segs, theme.Selection, selected)
	}
	rightLines = fitLines(rightLines, contentRows)

	title := "Search: " + m.settingsSearchQuery
	lines := make([]string, 0, height)
	lines = append(lines, m.settingsLeftTopLine(leftWidth, "Categories", leftFocused)+m.settingsRightTopLine(rightWidth, title, rightFocused))
	for i := 0; i < contentRows; i++ {
		lines = append(lines, m.settingsLeftContentLine(leftWidth, leftLines[i], leftFocused)+m.settingsRightContentLine(rightWidth, rightLines[i], rightFocused))
	}
	lines = append(lines, m.settingsLeftBottomLine(leftWidth, leftFocused)+m.settingsRightBottomLine(rightWidth, rightFocused))
	lines = append(lines, m.settingsFooterLine())
	return strings.Join(lines, "\n")
}
