package tui

import (
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/n-orlov/deck/internal/config"
	"github.com/n-orlov/deck/internal/theme"
)

// This file is task 013's `,` settings full-screen takeover skeleton (SPEC
// §11.5): a category list on the left, the selected category's field list
// on the right, both generated by walking internal/config.Schema rather
// than a second, hand-written field set (the exact defect requirement 22
// exists to catch). Navigation beyond "open, close" (tab/left/right/up/
// down, `/` fuzzy search), per-kind rendering, save/discard and the env-
// override label are tasks 014-018; this file only lays the frame down and
// proves it walks the schema and stays inside the terminal's budget.

// settingsCategory groups the schema fields that share one Field.Section
// under one human category name for the takeover's left-hand list.
type settingsCategory struct {
	Name    string
	Section string
	Fields  []config.Field
}

// settingsCategoryName maps a schema Field.Section to the takeover's
// human category label. Recorded here (rather than left to whichever task
// first needed a name) since task 013's notes flagged this as a decision
// to make and record: "" (config.toml's own top level) is "General", "ui"
// is "UI", "env" is "Environment" — matching config.toml's own section
// names for anything not top-level, since that is what a user editing the
// file by hand already sees.
func settingsCategoryName(section string) string {
	switch section {
	case "":
		return "General"
	case "ui":
		return "UI"
	case "env":
		return "Environment"
	case "notify":
		return "Notify"
	default:
		return strings.ToUpper(section[:1]) + section[1:]
	}
}

// settingsCategories walks config.Schema exactly once, grouping fields by
// Section in the order each section is first seen (schema.go already lists
// "", then "ui", then "env" contiguously, but this does not assume that —
// a schema field reordered or a new section inserted between others still
// groups correctly). This is the one and only place tasks 013-018 read the
// schema to build the takeover's category/field lists: neither list is
// ever hand-written alongside it.
func settingsCategories() []settingsCategory {
	var categories []settingsCategory
	indexBySection := map[string]int{}
	for _, field := range config.Schema {
		i, ok := indexBySection[field.Section]
		if !ok {
			i = len(categories)
			indexBySection[field.Section] = i
			categories = append(categories, settingsCategory{
				Name:    settingsCategoryName(field.Section),
				Section: field.Section,
			})
		}
		categories[i].Fields = append(categories[i].Fields, field)
	}
	// [notify] is deliberately absent from config.Schema (schema.go's own
	// comment: it is "the stated structural exception", edited via its own
	// dialog per §11.5 rather than flattened into fields). That dialog does
	// not exist this phase (task 029 adds no new dialog), so settings still
	// owes it "a single navigable entry" (§11.5) -- synthesized here, in the
	// TUI layer only, never added to config.Schema itself: task 018's parity
	// test walks config.Schema, and this entry has no backing schema field
	// to be found missing from.
	categories = append(categories, settingsCategory{
		Name:    settingsCategoryName("notify"),
		Section: "notify",
		Fields:  []config.Field{settingsNotifyEntry()},
	})
	return categories
}

// settingsNotifyEntry is the synthetic §11.5 "single navigable entry" for
// [notify]: a config.Field the settings takeover renders and lets the user
// select, but which config.Schema never declares and config.FileConfig has
// no member for. Its Kind is KindLink (the exact kind §11.5 reserves for
// "opens the owning dialog"), but activating it opens nothing this phase
// (task 029 adds no notification-rules dialog) -- settingsFieldValueDisplay
// and settingsActivateField both say so explicitly rather than pretending
// the link works.
func settingsNotifyEntry() config.Field {
	return config.Field{
		Section: "notify",
		Kind:    config.KindLink,
		Description: "Channels and delivery rules (SPEC §10) are structured tables " +
			"meant to be edited in their own notification-rules dialog (§11.4), not " +
			"flattened into fields here. That dialog is not implemented this phase: " +
			"this entry is honestly unavailable and opens nothing. Edit [notify] and " +
			"[[notify.rule]] by hand in config.toml until it lands.",
		Scope: config.ScopeGlobal,
	}
}

// settingsFieldLabel renders a schema Field's human label for the
// takeover's field list: the key's underscore-separated words, each
// capitalised ("recent_cwd_limit" -> "Recent Cwd Limit"). The [env] table
// field (Key == "", Section == "env") has no key to derive a label from —
// it is named for what it is instead.
func settingsFieldLabel(f config.Field) string {
	if f.Key == "" && f.Section == "notify" {
		return "Notification Rules"
	}
	if f.Key == "" {
		return "Environment Variables"
	}
	words := strings.Split(f.Key, "_")
	for i, w := range words {
		if w == "" {
			continue
		}
		words[i] = strings.ToUpper(w[:1]) + w[1:]
	}
	return strings.Join(words, " ")
}

// settingsFocus values name which of the takeover's two lists currently
// receives up/down navigation. SPEC §11.5: "tab/left/right switch between
// the category list and the field list, up/down move within the focused
// list."
const (
	settingsFocusCategories = 0
	settingsFocusFields     = 1
)

// updateSettings handles key input while the takeover is open. Task 016
// still owns ctrl+s (save) and turning esc-with-no-changes into a discard
// prompt; this task (014) owns tab/left/right focus switching, up/down
// list movement (wrapping, like every other cycled selection in this
// package -- see cycleOption/updateCreate's tab handling) and `/`'s fuzzy
// search over every field's label AND description.
func (m Model) updateSettings(msg tea.KeyMsg) (Model, tea.Cmd) {
	if m.settingsSearchActive {
		return m.updateSettingsSearch(msg)
	}
	switch msg.String() {
	case "esc":
		m.settingsOpen = false
	case "tab", "left", "right":
		if m.settingsFocus == settingsFocusCategories {
			m.settingsFocus = settingsFocusFields
		} else {
			m.settingsFocus = settingsFocusCategories
		}
	case "up", "k":
		m.settingsMove(-1)
	case "down", "j":
		m.settingsMove(1)
	case "enter", " ":
		m.settingsActivateField()
	case "+", "=":
		m.settingsAdjustField(1)
	case "-", "_":
		m.settingsAdjustField(-1)
	case "/":
		m.settingsSearchActive = true
		m.settingsSearchQuery = ""
		m.settingsSearchIndex = 0
	}
	return m, nil
}

// settingsMove moves the currently focused list's selection by delta,
// wrapping like every other cycled selection in this package. Moving the
// category list resets the field index to 0, since a category swap always
// starts the field list over at its own top (mirroring settingsView's own
// "open on category 0's first field" default).
func (m *Model) settingsMove(delta int) {
	categories := settingsCategories()
	if len(categories) == 0 {
		return
	}
	switch m.settingsFocus {
	case settingsFocusCategories:
		n := len(categories)
		m.settingsCategoryIndex = (m.settingsCategoryIndex + delta + n) % n
		m.settingsFieldIndex = 0
	case settingsFocusFields:
		if m.settingsCategoryIndex < 0 || m.settingsCategoryIndex >= len(categories) {
			return
		}
		fields := categories[m.settingsCategoryIndex].Fields
		if len(fields) == 0 {
			return
		}
		n := len(fields)
		m.settingsFieldIndex = (m.settingsFieldIndex + delta + n) % n
	}
}

// settingsSelectedField returns the field the field-list focus currently
// sits on, or ok=false when categories has focus (nothing to edit there) or
// either index is out of range (an empty category, or a stale index left
// over from a category swap this call raced with the schema -- neither
// happens in practice since settingsMove always resets settingsFieldIndex
// to 0 on a category change, but settingsActivateField/settingsAdjustField
// stay defensive rather than index a slice on trust).
func (m *Model) settingsSelectedField() (config.Field, bool) {
	if m.settingsFocus != settingsFocusFields {
		return config.Field{}, false
	}
	categories := settingsCategories()
	if m.settingsCategoryIndex < 0 || m.settingsCategoryIndex >= len(categories) {
		return config.Field{}, false
	}
	fields := categories[m.settingsCategoryIndex].Fields
	if m.settingsFieldIndex < 0 || m.settingsFieldIndex >= len(fields) {
		return config.Field{}, false
	}
	return fields[m.settingsFieldIndex], true
}

// settingsActivateField is enter/space's effect on the focused field: it
// flips a KindToggle field's staged value and otherwise does nothing --
// notably including the [notify] KindLink entry, which §11.5 would have
// open the notification-rules dialog if one existed. Task 029 adds no such
// dialog this phase, so activating the entry is a documented no-op rather
// than a key that silently fails to do what it claims: settingsFieldValue-
// Display already renders that entry's value as "unavailable this phase".
func (m *Model) settingsActivateField() {
	f, ok := m.settingsSelectedField()
	if !ok {
		return
	}
	if f.Kind == config.KindToggle {
		settingsSetToggle(&m.settingsEdits, f, !settingsToggleValue(f, m.settingsEdits))
	}
}

// settingsAdjustField is +/-'s effect on the focused field: step a
// KindInteger field's staged value by delta (settingsSetInteger clamps to
// the field's declared Bounds, so this can never stage a value the file
// writer or the schema-driven parser would reject), or cycle a KindEnum
// field's staged value through settingsFieldOptions. Every other kind has
// no notion of a "next" value and is left untouched.
func (m *Model) settingsAdjustField(delta int) {
	f, ok := m.settingsSelectedField()
	if !ok {
		return
	}
	switch f.Kind {
	case config.KindInteger:
		settingsSetInteger(&m.settingsEdits, f, settingsIntegerValue(f, m.settingsEdits)+delta)
	case config.KindEnum:
		options := m.settingsFieldOptions(f)
		if len(options) == 0 {
			return
		}
		cur := settingsEnumValue(f, m.settingsEdits)
		idx := 0
		for i, o := range options {
			if o == cur {
				idx = i
			}
		}
		idx = ((idx+delta)%len(options) + len(options)) % len(options)
		settingsSetEnum(&m.settingsEdits, f, options[idx])
	}
}

// settingsEditsFromSettings seeds the takeover's staged working copy
// (Model.settingsEdits) from the already-resolved config.Settings the rest
// of the program uses, the one time it needs to: when `,` opens the
// takeover. Every member here mirrors a real config.FileConfig member a
// real Settings field was itself loaded from (see config.Settings' own
// doc comments) -- Theme is the one exception, since Settings keeps only
// the already-*resolved* theme.Theme plus a fallback reason, not the raw
// configured name; m.settings.Theme.Name (the resolved theme actually in
// effect) is the closest honest approximation available without re-reading
// config.toml's raw ui.theme value here.
func settingsEditsFromSettings(s config.Settings) config.FileConfig {
	themeName := ""
	if s.Theme != nil {
		themeName = s.Theme.Name
	}
	return config.FileConfig{
		AllowYolo:          s.AllowYolo,
		StaleAfter:         s.StaleAfter,
		CaptureMinInterval: s.CaptureMinInterval,
		ASCII:              s.ASCII,
		Mouse:              s.Mouse,
		RecentCwdLimit:     s.RecentCwdLimit,
		Theme:              themeName,
		Env:                settingsCloneEnv(s.Env),
	}
}

func settingsCloneEnv(env map[string]string) map[string]string {
	if env == nil {
		return nil
	}
	out := make(map[string]string, len(env))
	for k, v := range env {
		out[k] = v
	}
	return out
}

// settingsToggleValue/settingsSetToggle, settingsIntegerValue/
// settingsSetInteger and settingsEnumValue/settingsSetEnum are the get/set
// pair for every KindToggle/KindInteger/KindEnum field config.Schema
// actually declares today. Each mirrors toml.go's setField and
// toml_write.go's serializeFieldValue: one generic dispatch per Kind, with
// a FullKey switch beneath it that carries no logic of its own (Go structs
// have no by-name-string field access without reflection) -- adding a
// future schema field of an already-supported kind means one case here,
// not a new code path.
func settingsToggleValue(f config.Field, cfg config.FileConfig) bool {
	switch f.FullKey() {
	case "allow_yolo":
		return cfg.AllowYolo
	case "ui.ascii":
		return cfg.ASCII
	case "ui.mouse":
		return cfg.Mouse
	default:
		b, _ := f.Default.(bool)
		return b
	}
}

func settingsSetToggle(cfg *config.FileConfig, f config.Field, v bool) {
	switch f.FullKey() {
	case "allow_yolo":
		cfg.AllowYolo = v
	case "ui.ascii":
		cfg.ASCII = v
	case "ui.mouse":
		cfg.Mouse = v
	}
}

func settingsIntegerValue(f config.Field, cfg config.FileConfig) int {
	switch f.FullKey() {
	case "stale_after":
		return int(cfg.StaleAfter.Seconds())
	case "capture_min_interval":
		return int(cfg.CaptureMinInterval.Seconds())
	case "ui.recent_cwd_limit":
		return cfg.RecentCwdLimit
	default:
		v, _ := f.Default.(int)
		return v
	}
}

// settingsSetInteger clamps v to field's declared IntBounds before writing
// it into cfg, so +/- (or a future direct-entry editor) can never stage an
// out-of-bounds value the atomic writer or the schema-driven reader would
// then have to reject on the next load.
func settingsSetInteger(cfg *config.FileConfig, f config.Field, v int) {
	if v < f.IntBounds.Min {
		v = f.IntBounds.Min
	}
	if f.IntBounds.Max != nil && v > *f.IntBounds.Max {
		v = *f.IntBounds.Max
	}
	switch f.FullKey() {
	case "stale_after":
		cfg.StaleAfter = time.Duration(v) * time.Second
	case "capture_min_interval":
		cfg.CaptureMinInterval = time.Duration(v) * time.Second
	case "ui.recent_cwd_limit":
		cfg.RecentCwdLimit = v
	}
}

func settingsEnumValue(f config.Field, cfg config.FileConfig) string {
	switch f.FullKey() {
	case "ui.theme":
		return cfg.Theme
	default:
		s, _ := f.Default.(string)
		return s
	}
}

func settingsSetEnum(cfg *config.FileConfig, f config.Field, v string) {
	switch f.FullKey() {
	case "ui.theme":
		cfg.Theme = v
	}
}

// settingsFieldOptions resolves a KindEnum field's cycle-through choices.
// ui.theme is §11.6's DynamicEnum case (schema.go: "the schema cannot list
// a fixed choice set because a dropped-in user theme file changes it
// without a code change"), so its options are resolved here, at render/
// edit time, from the same theme.Builtins()/theme.DiscoverUserThemes the
// rest of the program uses to resolve a configured name -- never a second,
// hand-maintained theme name list.
func (m Model) settingsFieldOptions(f config.Field) []string {
	switch f.FullKey() {
	case "ui.theme":
		return settingsThemeOptions(m.settings.Paths)
	default:
		return f.EnumValues
	}
}

func settingsThemeOptions(paths config.Paths) []string {
	var names []string
	for _, t := range theme.Builtins() {
		names = append(names, t.Name)
	}
	sort.Strings(names)
	userThemes, _ := theme.DiscoverUserThemes(theme.ThemesDir(paths.ConfigFile))
	var userNames []string
	for name := range userThemes {
		userNames = append(userNames, name)
	}
	sort.Strings(userNames)
	return append(names, userNames...)
}

// settingsFieldValueDisplay renders field f's current staged value (from
// cfg) exactly as §11.5 requires per kind: On/Off for a toggle, the number
// plus its declared unit and bounds for a bounded integer, the raw string
// for a plain string, a path collapsed back to `~` form for KindPath (the
// display-side counterpart of expandCreateCWD's ~-expansion, task 011.7),
// the selected choice for an enum, an entry count for list-of-strings, and
// the honest "unavailable this phase" for [notify]'s KindLink entry rather
// than a value it does not have. Every kind config.FieldKind names is
// handled explicitly, including the three (string, path, link other than
// notify) config.Schema happens not to use today, so a future schema
// addition of one of those kinds renders correctly on day one.
func settingsFieldValueDisplay(f config.Field, cfg config.FileConfig) string {
	switch f.Kind {
	case config.KindToggle:
		if settingsToggleValue(f, cfg) {
			return "On"
		}
		return "Off"
	case config.KindInteger:
		v := settingsIntegerValue(f, cfg)
		text := strconv.Itoa(v)
		if f.Unit != "" {
			text += " " + f.Unit
		}
		if bounds := settingsIntegerBoundsText(f); bounds != "" {
			text += " (" + bounds + ")"
		}
		return text
	case config.KindEnum:
		v := settingsEnumValue(f, cfg)
		if v == "" {
			return "(default)"
		}
		return v
	case config.KindString:
		return settingsStringValue(f, cfg)
	case config.KindPath:
		return settingsCollapseTilde(settingsStringValue(f, cfg))
	case config.KindListOfStrings:
		return settingsListValueDisplay(f, cfg)
	case config.KindLink:
		if f.Section == "notify" {
			return "unavailable this phase"
		}
		return "opens its own dialog"
	default:
		return fmt.Sprintf("%v", f.Default)
	}
}

// settingsIntegerBoundsText renders a KindInteger field's declared Bounds
// as the parenthetical settingsFieldValueDisplay appends, e.g. "1-50" or
// "min 1" when there is no documented upper bound (Bounds.Max == nil).
func settingsIntegerBoundsText(f config.Field) string {
	if f.Kind != config.KindInteger {
		return ""
	}
	if f.IntBounds.Max != nil {
		return fmt.Sprintf("%d-%d", f.IntBounds.Min, *f.IntBounds.Max)
	}
	return fmt.Sprintf("min %d", f.IntBounds.Min)
}

// settingsStringValue is KindString's get, generic across any future
// schema field of that kind: config.Schema declares none today, so this
// only ever falls through to the field's declared Default, but the
// dispatch shape matches settingsToggleValue/settingsIntegerValue/
// settingsEnumValue exactly so adding a real KindString field later is one
// case here, not a new function.
func settingsStringValue(f config.Field, cfg config.FileConfig) string {
	_ = cfg // no schema field of KindString exists yet to read out of cfg
	switch f.FullKey() {
	default:
		s, _ := f.Default.(string)
		return s
	}
}

// settingsCollapseTilde is the display-side inverse of tui.go's
// expandCreateCWD: a path under the current user's home directory renders
// with that prefix collapsed to `~`, matching how a user who typed `~/...`
// into a path field would expect to see it read back, rather than the
// fully-expanded absolute form expandCreateCWD stores. A path outside the
// home directory, or one os.UserHomeDir cannot resolve, is returned
// unchanged.
func settingsCollapseTilde(path string) string {
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		return path
	}
	if path == home {
		return "~"
	}
	if strings.HasPrefix(path, home+string(os.PathSeparator)) {
		return "~" + path[len(home):]
	}
	return path
}

// settingsListValueDisplay is KindListOfStrings' get. [env] (Key == "") is
// the one real schema field of this kind: its "list" is really a
// KEY=VALUE map, so rendering every entry inline would crowd the field
// list (and leak env values into a screenshot); an entry count is shown
// instead, matching §11.5's own framing of [env] as "opens" the concept of
// many entries rather than one flat value (the actual per-entry editor
// this implies is out of scope for task 015, which owns per-kind display,
// not a nested table editor -- see settingsFieldDetailLines' description
// text for the honest statement of what changing it does).
func settingsListValueDisplay(f config.Field, cfg config.FileConfig) string {
	if f.FullKey() == "[env]" {
		n := len(cfg.Env)
		switch n {
		case 0:
			return "0 entries"
		case 1:
			return "1 entry"
		default:
			return fmt.Sprintf("%d entries", n)
		}
	}
	if list, ok := f.Default.([]string); ok {
		if len(list) == 0 {
			return "(empty)"
		}
		return strings.Join(list, ", ")
	}
	return "(empty)"
}

// settingsFieldDetailLines renders the currently selected field's kind,
// scope and description underneath its own row in the field list --
// §11.5's "each field states what it does and what changes when it
// changes" plus the scope label requirement, both read verbatim off the
// schema Field rather than a second, hand-written copy of either. width is
// the field panel's usable content width; wrapText keeps a long
// description from being truncated away instead of wrapped across lines.
func settingsFieldDetailLines(f config.Field, width int) []string {
	if width < 1 {
		width = 1
	}
	lines := []string{fmt.Sprintf("Kind: %s \u00b7 Scope: %s", f.Kind, f.Scope)}
	lines = append(lines, wrapText(f.Description, width)...)
	return lines
}

// settingsSearchResult pairs a schema field matched by a `/` query with the
// category/field indices selecting it (enter, task 014) or rendering it
// (task 015) lands on.
type settingsSearchResult struct {
	CategoryIndex int
	FieldIndex    int
	Field         config.Field
}

// settingsFuzzyMatch is the small "fuzzy" §11.5's field search needs: every
// whitespace-separated token of query must appear as a case-insensitive
// substring of target, in any order. A query of "" matches everything (the
// search box starts empty and shows every field until the user types).
func settingsFuzzyMatch(query, target string) bool {
	target = strings.ToLower(target)
	for _, tok := range strings.Fields(strings.ToLower(query)) {
		if !strings.Contains(target, tok) {
			return false
		}
	}
	return true
}

// settingsSearchMatches searches every schema field's label AND
// description (§11.5: "/ ... searches every field by label and
// description") and returns matches in schema order, each carrying the
// category/field indices that select it.
func settingsSearchMatches(query string) []settingsSearchResult {
	var results []settingsSearchResult
	for ci, cat := range settingsCategories() {
		for fi, f := range cat.Fields {
			label := settingsFieldLabel(f)
			if settingsFuzzyMatch(query, label) || settingsFuzzyMatch(query, f.Description) {
				results = append(results, settingsSearchResult{CategoryIndex: ci, FieldIndex: fi, Field: f})
			}
		}
	}
	return results
}

// updateSettingsSearch handles key input while the `/` search box is
// active: typed runes extend the query, backspace shortens it, up/down
// move among the current matches, enter jumps the two lists to the
// highlighted match and leaves search mode with focus on the field list,
// and esc leaves search mode (clearing the query) without moving the
// selection -- mirroring the closing-without-saving shape task 016 will
// give the takeover as a whole, but scoped to just the search box.
func (m Model) updateSettingsSearch(msg tea.KeyMsg) (Model, tea.Cmd) {
	switch msg.String() {
	case "esc":
		m.settingsSearchActive = false
		m.settingsSearchQuery = ""
		m.settingsSearchIndex = 0
		return m, nil
	case "enter":
		results := settingsSearchMatches(m.settingsSearchQuery)
		if m.settingsSearchIndex >= 0 && m.settingsSearchIndex < len(results) {
			match := results[m.settingsSearchIndex]
			m.settingsCategoryIndex = match.CategoryIndex
			m.settingsFieldIndex = match.FieldIndex
			m.settingsFocus = settingsFocusFields
		}
		m.settingsSearchActive = false
		m.settingsSearchQuery = ""
		m.settingsSearchIndex = 0
		return m, nil
	case "backspace", "ctrl+h":
		if q := m.settingsSearchQuery; q != "" {
			r := []rune(q)
			m.settingsSearchQuery = string(r[:len(r)-1])
		}
		m.settingsSearchIndex = 0
		return m, nil
	case "up", "ctrl+p":
		if n := len(settingsSearchMatches(m.settingsSearchQuery)); n > 0 {
			m.settingsSearchIndex = (m.settingsSearchIndex - 1 + n) % n
		}
		return m, nil
	case "down", "ctrl+n":
		if n := len(settingsSearchMatches(m.settingsSearchQuery)); n > 0 {
			m.settingsSearchIndex = (m.settingsSearchIndex + 1) % n
		}
		return m, nil
	}
	if runes := msg.Runes; len(runes) > 0 {
		m.settingsSearchQuery += string(runes)
		m.settingsSearchIndex = 0
	}
	return m, nil
}

// settingsCategoryWidth picks the left category panel's width the same way
// ComputeLayout picks the sidebar's: a fraction of the total width, clamped
// to a floor that keeps every category name legible and a ceiling that
// leaves the field list (the panel that actually carries the field's
// description text, task 015) the majority of the screen.
func settingsCategoryWidth(width int) int {
	w := width / 3
	const floor, ceil = 20, 30
	if w < floor {
		w = floor
	}
	if w > ceil {
		w = ceil
	}
	if width-w < floor {
		w = width - floor
	}
	if w < 1 {
		w = 1
	}
	return w
}

// settingsView renders the full-screen takeover: a category list panel and
// a field list panel sharing one seam, reusing the exact border-drawing
// helpers the main side-by-side frame already uses (panel.go's
// sidebarTopLine/sidebarContentLine/sidebarBottomLine for the left panel,
// previewTopLine/previewContentLine/previewBottomLine with seam=true for
// the right) rather than a second box-drawing implementation — SPEC
// requirement 16's "bordered like every other panel, dialog and overlay"
// with one geometry, not two.
func (m Model) settingsView() string {
	width, height := m.frameSize()
	leftWidth := settingsCategoryWidth(width)
	rightWidth := width - leftWidth
	// One row for the top border, one for the bottom border, one for the
	// footer line below the frame (mirroring mainView's own footerLine).
	contentRows := height - 3
	if contentRows < 0 {
		contentRows = 0
	}

	categories := settingsCategories()

	if m.settingsSearchActive {
		return m.settingsSearchViewLines(categories, leftWidth, rightWidth, contentRows, height)
	}

	leftLines := make([]string, len(categories))
	for i, cat := range categories {
		marker := "  "
		if i == m.settingsCategoryIndex {
			marker = "> "
		}
		leftLines[i] = marker + cat.Name
	}
	leftLines = fitLines(leftLines, contentRows)

	var rightLines []string
	if m.settingsCategoryIndex >= 0 && m.settingsCategoryIndex < len(categories) {
		fields := categories[m.settingsCategoryIndex].Fields
		innerWidth := rightWidth - 4
		for i, f := range fields {
			marker := "  "
			if i == m.settingsFieldIndex {
				marker = "> "
			}
			rightLines = append(rightLines, marker+settingsFieldLabel(f)+": "+settingsFieldValueDisplay(f, m.settingsEdits))
			if i == m.settingsFieldIndex {
				for _, detail := range settingsFieldDetailLines(f, innerWidth-2) {
					rightLines = append(rightLines, "    "+detail)
				}
			}
		}
	}
	rightLines = fitLines(rightLines, contentRows)

	lines := make([]string, 0, height)
	lines = append(lines, m.sidebarTopLine(leftWidth, "Categories")+m.previewTopLine(rightWidth, "Fields", true))
	for i := 0; i < contentRows; i++ {
		lines = append(lines, m.sidebarContentLine(leftWidth, leftLines[i])+m.previewContentLine(rightWidth, rightLines[i]))
	}
	lines = append(lines, m.sidebarBottomLine(leftWidth)+m.previewBottomLine(rightWidth, true))
	lines = append(lines, m.settingsFooterLine())
	return strings.Join(lines, "\n")
}

// settingsFooterLine names every key the takeover currently binds:
// task 013's esc, task 014's tab/left/right/up-down/`/`, and task 015's
// enter/space (toggle) and +/- (adjust a bounded integer or cycle an
// enum) -- never a key bound here but left unnamed, the same "advertises
// a key it doesn't grant"/"binds a key it doesn't name" defect the §11.4
// dialog contract (task 029) forbids for the five dialogs. Task 016
// extends this line again once ctrl+s save lands.
func (m Model) settingsFooterLine() string {
	if m.settingsSearchActive {
		return "type to search - up/down select - enter jump - esc cancel"
	}
	return "tab/left/right switch - up/down move - enter/+/- edit - / search - esc close"
}

// settingsSearchViewLines renders the takeover while `/`'s search box is
// active: the left panel keeps showing the category list unchanged (search
// spans every category, so no single category is "selected" while
// searching), and the right panel's title carries the typed query and its
// content becomes the flat, cross-category list settingsSearchMatches
// returns, each row prefixed with its own category name so a match from a
// category other than the one open before `/` was pressed is not mistaken
// for one of the still-shown left panel's category.
func (m Model) settingsSearchViewLines(categories []settingsCategory, leftWidth, rightWidth, contentRows, height int) string {
	leftLines := make([]string, len(categories))
	for i, cat := range categories {
		leftLines[i] = "  " + cat.Name
	}
	leftLines = fitLines(leftLines, contentRows)

	results := settingsSearchMatches(m.settingsSearchQuery)
	rightLines := make([]string, len(results))
	for i, r := range results {
		marker := "  "
		if i == m.settingsSearchIndex {
			marker = "> "
		}
		rightLines[i] = marker + categories[r.CategoryIndex].Name + ": " + settingsFieldLabel(r.Field)
	}
	rightLines = fitLines(rightLines, contentRows)

	title := "Search: " + m.settingsSearchQuery
	lines := make([]string, 0, height)
	lines = append(lines, m.sidebarTopLine(leftWidth, "Categories")+m.previewTopLine(rightWidth, title, true))
	for i := 0; i < contentRows; i++ {
		lines = append(lines, m.sidebarContentLine(leftWidth, leftLines[i])+m.previewContentLine(rightWidth, rightLines[i]))
	}
	lines = append(lines, m.sidebarBottomLine(leftWidth)+m.previewBottomLine(rightWidth, true))
	lines = append(lines, m.settingsFooterLine())
	return strings.Join(lines, "\n")
}
