package tui

import (
	"strings"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/n-orlov/deck/internal/config"
)

// This file is task 013's `,` settings full-screen takeover skeleton (SPEC
// §11.5): a category list on the left, the selected category's field list
// on the right, both generated by walking internal/config.Schema rather
// than a second, hand-written field set (the exact defect requirement 22
// exists to catch). Navigation beyond "open, close" (tab/left/right/up/
// down, `/` fuzzy search), per-kind rendering, save/discard and the env-
// override label are tasks 014-018; this file only lays the frame down and
// proves it walks the schema and stays inside the terminal's budget.

// settingsCategory groups the schema fields that share one Field.Section
// under one human category name for the takeover's left-hand list.
type settingsCategory struct {
	Name    string
	Section string
	Fields  []config.Field
}

// settingsCategoryName maps a schema Field.Section to the takeover's
// human category label. Recorded here (rather than left to whichever task
// first needed a name) since task 013's notes flagged this as a decision
// to make and record: "" (config.toml's own top level) is "General", "ui"
// is "UI", "env" is "Environment" — matching config.toml's own section
// names for anything not top-level, since that is what a user editing the
// file by hand already sees.
func settingsCategoryName(section string) string {
	switch section {
	case "":
		return "General"
	case "ui":
		return "UI"
	case "env":
		return "Environment"
	default:
		return strings.ToUpper(section[:1]) + section[1:]
	}
}

// settingsCategories walks config.Schema exactly once, grouping fields by
// Section in the order each section is first seen (schema.go already lists
// "", then "ui", then "env" contiguously, but this does not assume that —
// a schema field reordered or a new section inserted between others still
// groups correctly). This is the one and only place tasks 013-018 read the
// schema to build the takeover's category/field lists: neither list is
// ever hand-written alongside it.
func settingsCategories() []settingsCategory {
	var categories []settingsCategory
	indexBySection := map[string]int{}
	for _, field := range config.Schema {
		i, ok := indexBySection[field.Section]
		if !ok {
			i = len(categories)
			indexBySection[field.Section] = i
			categories = append(categories, settingsCategory{
				Name:    settingsCategoryName(field.Section),
				Section: field.Section,
			})
		}
		categories[i].Fields = append(categories[i].Fields, field)
	}
	return categories
}

// settingsFieldLabel renders a schema Field's human label for the
// takeover's field list: the key's underscore-separated words, each
// capitalised ("recent_cwd_limit" -> "Recent Cwd Limit"). The [env] table
// field (Key == "", Section == "env") has no key to derive a label from —
// it is named for what it is instead.
func settingsFieldLabel(f config.Field) string {
	if f.Key == "" {
		return "Environment Variables"
	}
	words := strings.Split(f.Key, "_")
	for i, w := range words {
		if w == "" {
			continue
		}
		words[i] = strings.ToUpper(w[:1]) + w[1:]
	}
	return strings.Join(words, " ")
}

// settingsFocus values name which of the takeover's two lists currently
// receives up/down navigation. SPEC §11.5: "tab/left/right switch between
// the category list and the field list, up/down move within the focused
// list."
const (
	settingsFocusCategories = 0
	settingsFocusFields     = 1
)

// updateSettings handles key input while the takeover is open. Task 016
// still owns ctrl+s (save) and turning esc-with-no-changes into a discard
// prompt; this task (014) owns tab/left/right focus switching, up/down
// list movement (wrapping, like every other cycled selection in this
// package -- see cycleOption/updateCreate's tab handling) and `/`'s fuzzy
// search over every field's label AND description.
func (m Model) updateSettings(msg tea.KeyMsg) (Model, tea.Cmd) {
	if m.settingsSearchActive {
		return m.updateSettingsSearch(msg)
	}
	switch msg.String() {
	case "esc":
		m.settingsOpen = false
	case "tab", "left", "right":
		if m.settingsFocus == settingsFocusCategories {
			m.settingsFocus = settingsFocusFields
		} else {
			m.settingsFocus = settingsFocusCategories
		}
	case "up", "k":
		m.settingsMove(-1)
	case "down", "j":
		m.settingsMove(1)
	case "/":
		m.settingsSearchActive = true
		m.settingsSearchQuery = ""
		m.settingsSearchIndex = 0
	}
	return m, nil
}

// settingsMove moves the currently focused list's selection by delta,
// wrapping like every other cycled selection in this package. Moving the
// category list resets the field index to 0, since a category swap always
// starts the field list over at its own top (mirroring settingsView's own
// "open on category 0's first field" default).
func (m *Model) settingsMove(delta int) {
	categories := settingsCategories()
	if len(categories) == 0 {
		return
	}
	switch m.settingsFocus {
	case settingsFocusCategories:
		n := len(categories)
		m.settingsCategoryIndex = (m.settingsCategoryIndex + delta + n) % n
		m.settingsFieldIndex = 0
	case settingsFocusFields:
		if m.settingsCategoryIndex < 0 || m.settingsCategoryIndex >= len(categories) {
			return
		}
		fields := categories[m.settingsCategoryIndex].Fields
		if len(fields) == 0 {
			return
		}
		n := len(fields)
		m.settingsFieldIndex = (m.settingsFieldIndex + delta + n) % n
	}
}

// settingsSearchResult pairs a schema field matched by a `/` query with the
// category/field indices selecting it (enter, task 014) or rendering it
// (task 015) lands on.
type settingsSearchResult struct {
	CategoryIndex int
	FieldIndex    int
	Field         config.Field
}

// settingsFuzzyMatch is the small "fuzzy" §11.5's field search needs: every
// whitespace-separated token of query must appear as a case-insensitive
// substring of target, in any order. A query of "" matches everything (the
// search box starts empty and shows every field until the user types).
func settingsFuzzyMatch(query, target string) bool {
	target = strings.ToLower(target)
	for _, tok := range strings.Fields(strings.ToLower(query)) {
		if !strings.Contains(target, tok) {
			return false
		}
	}
	return true
}

// settingsSearchMatches searches every schema field's label AND
// description (§11.5: "/ ... searches every field by label and
// description") and returns matches in schema order, each carrying the
// category/field indices that select it.
func settingsSearchMatches(query string) []settingsSearchResult {
	var results []settingsSearchResult
	for ci, cat := range settingsCategories() {
		for fi, f := range cat.Fields {
			label := settingsFieldLabel(f)
			if settingsFuzzyMatch(query, label) || settingsFuzzyMatch(query, f.Description) {
				results = append(results, settingsSearchResult{CategoryIndex: ci, FieldIndex: fi, Field: f})
			}
		}
	}
	return results
}

// updateSettingsSearch handles key input while the `/` search box is
// active: typed runes extend the query, backspace shortens it, up/down
// move among the current matches, enter jumps the two lists to the
// highlighted match and leaves search mode with focus on the field list,
// and esc leaves search mode (clearing the query) without moving the
// selection -- mirroring the closing-without-saving shape task 016 will
// give the takeover as a whole, but scoped to just the search box.
func (m Model) updateSettingsSearch(msg tea.KeyMsg) (Model, tea.Cmd) {
	switch msg.String() {
	case "esc":
		m.settingsSearchActive = false
		m.settingsSearchQuery = ""
		m.settingsSearchIndex = 0
		return m, nil
	case "enter":
		results := settingsSearchMatches(m.settingsSearchQuery)
		if m.settingsSearchIndex >= 0 && m.settingsSearchIndex < len(results) {
			match := results[m.settingsSearchIndex]
			m.settingsCategoryIndex = match.CategoryIndex
			m.settingsFieldIndex = match.FieldIndex
			m.settingsFocus = settingsFocusFields
		}
		m.settingsSearchActive = false
		m.settingsSearchQuery = ""
		m.settingsSearchIndex = 0
		return m, nil
	case "backspace", "ctrl+h":
		if q := m.settingsSearchQuery; q != "" {
			r := []rune(q)
			m.settingsSearchQuery = string(r[:len(r)-1])
		}
		m.settingsSearchIndex = 0
		return m, nil
	case "up", "ctrl+p":
		if n := len(settingsSearchMatches(m.settingsSearchQuery)); n > 0 {
			m.settingsSearchIndex = (m.settingsSearchIndex - 1 + n) % n
		}
		return m, nil
	case "down", "ctrl+n":
		if n := len(settingsSearchMatches(m.settingsSearchQuery)); n > 0 {
			m.settingsSearchIndex = (m.settingsSearchIndex + 1) % n
		}
		return m, nil
	}
	if runes := msg.Runes; len(runes) > 0 {
		m.settingsSearchQuery += string(runes)
		m.settingsSearchIndex = 0
	}
	return m, nil
}

// settingsCategoryWidth picks the left category panel's width the same way
// ComputeLayout picks the sidebar's: a fraction of the total width, clamped
// to a floor that keeps every category name legible and a ceiling that
// leaves the field list (the panel that actually carries the field's
// description text, task 015) the majority of the screen.
func settingsCategoryWidth(width int) int {
	w := width / 3
	const floor, ceil = 20, 30
	if w < floor {
		w = floor
	}
	if w > ceil {
		w = ceil
	}
	if width-w < floor {
		w = width - floor
	}
	if w < 1 {
		w = 1
	}
	return w
}

// settingsView renders the full-screen takeover: a category list panel and
// a field list panel sharing one seam, reusing the exact border-drawing
// helpers the main side-by-side frame already uses (panel.go's
// sidebarTopLine/sidebarContentLine/sidebarBottomLine for the left panel,
// previewTopLine/previewContentLine/previewBottomLine with seam=true for
// the right) rather than a second box-drawing implementation — SPEC
// requirement 16's "bordered like every other panel, dialog and overlay"
// with one geometry, not two.
func (m Model) settingsView() string {
	width, height := m.frameSize()
	leftWidth := settingsCategoryWidth(width)
	rightWidth := width - leftWidth
	// One row for the top border, one for the bottom border, one for the
	// footer line below the frame (mirroring mainView's own footerLine).
	contentRows := height - 3
	if contentRows < 0 {
		contentRows = 0
	}

	categories := settingsCategories()

	if m.settingsSearchActive {
		return m.settingsSearchViewLines(categories, leftWidth, rightWidth, contentRows, height)
	}

	leftLines := make([]string, len(categories))
	for i, cat := range categories {
		marker := "  "
		if i == m.settingsCategoryIndex {
			marker = "> "
		}
		leftLines[i] = marker + cat.Name
	}
	leftLines = fitLines(leftLines, contentRows)

	var rightLines []string
	if m.settingsCategoryIndex >= 0 && m.settingsCategoryIndex < len(categories) {
		fields := categories[m.settingsCategoryIndex].Fields
		rightLines = make([]string, len(fields))
		for i, f := range fields {
			marker := "  "
			if i == m.settingsFieldIndex {
				marker = "> "
			}
			rightLines[i] = marker + settingsFieldLabel(f)
		}
	}
	rightLines = fitLines(rightLines, contentRows)

	lines := make([]string, 0, height)
	lines = append(lines, m.sidebarTopLine(leftWidth, "Categories")+m.previewTopLine(rightWidth, "Fields", true))
	for i := 0; i < contentRows; i++ {
		lines = append(lines, m.sidebarContentLine(leftWidth, leftLines[i])+m.previewContentLine(rightWidth, rightLines[i]))
	}
	lines = append(lines, m.sidebarBottomLine(leftWidth)+m.previewBottomLine(rightWidth, true))
	lines = append(lines, m.settingsFooterLine())
	return strings.Join(lines, "\n")
}

// settingsFooterLine states only the one key task 013 actually binds
// (esc). Naming a key the takeover does not yet act on here would be the
// same "advertises a key it doesn't grant" defect the §11.4 dialog
// contract (task 029) forbids for the five dialogs; tasks 014/016 extend
// this line as navigation, search and save land.
func (m Model) settingsFooterLine() string {
	if m.settingsSearchActive {
		return "type to search - up/down select - enter jump - esc cancel"
	}
	return "tab/left/right switch - up/down move - / search - esc close"
}

// settingsSearchViewLines renders the takeover while `/`'s search box is
// active: the left panel keeps showing the category list unchanged (search
// spans every category, so no single category is "selected" while
// searching), and the right panel's title carries the typed query and its
// content becomes the flat, cross-category list settingsSearchMatches
// returns, each row prefixed with its own category name so a match from a
// category other than the one open before `/` was pressed is not mistaken
// for one of the still-shown left panel's category.
func (m Model) settingsSearchViewLines(categories []settingsCategory, leftWidth, rightWidth, contentRows, height int) string {
	leftLines := make([]string, len(categories))
	for i, cat := range categories {
		leftLines[i] = "  " + cat.Name
	}
	leftLines = fitLines(leftLines, contentRows)

	results := settingsSearchMatches(m.settingsSearchQuery)
	rightLines := make([]string, len(results))
	for i, r := range results {
		marker := "  "
		if i == m.settingsSearchIndex {
			marker = "> "
		}
		rightLines[i] = marker + categories[r.CategoryIndex].Name + ": " + settingsFieldLabel(r.Field)
	}
	rightLines = fitLines(rightLines, contentRows)

	title := "Search: " + m.settingsSearchQuery
	lines := make([]string, 0, height)
	lines = append(lines, m.sidebarTopLine(leftWidth, "Categories")+m.previewTopLine(rightWidth, title, true))
	for i := 0; i < contentRows; i++ {
		lines = append(lines, m.sidebarContentLine(leftWidth, leftLines[i])+m.previewContentLine(rightWidth, rightLines[i]))
	}
	lines = append(lines, m.sidebarBottomLine(leftWidth)+m.previewBottomLine(rightWidth, true))
	lines = append(lines, m.settingsFooterLine())
	return strings.Join(lines, "\n")
}
